version: "3.6"

services:
  ark-se-server:
    build:
      context: .
      dockerfile: docker/ark-se-dedicated-server.Dockerfile
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    restart: unless-stopped
    user: "1000:1000"
    environment:
      - "ADMIN_PASSWORD=changeme"
      - "GAME_PORT=7777"
      - "GAME_PORT_2=7778"
      - "GAME_VERSION=public"
      - "MAP_NAME=TheIsland"
      - "MAX_PLAYERS=16"
      - "QUERY_PORT=27015"
      - "SERVER_NAME=ArkSeServer"
      - "SERVER_PASSWORD="
    ports:
      - target: 7777
        published: 7777
        protocol: udp
      - target: 7778
        published: 7778
        protocol: udp
      - target: 27015
        published: 27015
        protocol: udp
    volumes:
      - ./ArkSE_Install:/home/steam/ArkSE_Install
      - ./ArkSE_Config:/home/steam/ArkSE_Install/ShooterGame/Saved
    cap_drop:
      - ALL
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
